DreamWoodz/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.staticfiles.urls import staticfiles_urlpatterns


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('facialRecognitionSite.urls', namespace="facialRocognitionUrls")),

]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)


urlpatterns += staticfiles_urlpatterns()

facialRecognitionSite/urls.py
from django.contrib import admin
from django.urls import path
from . import views
from django.contrib.staticfiles.urls import staticfiles_urlpatterns
from rest_framework.urlpatterns import format_suffix_patterns


app_name = "facialRocognitionUrls"


urlpatterns = [
    path('home/<str:pk>/', views.home_view, name='indexPage'),
    path('about/<str:pk>/', views.AboutView.as_view(), name='aboutPage'),
    path('', views.AccountView.as_view(), name='accountPage'),
    path('bed/<str:pk>/', views.BedView.as_view(), name='bedPage'),
    path('chair/<str:pk>/', views.ChairView.as_view(), name='chairPage'),
    path('contacts/<str:pk>/', views.ContactsView.as_view(), name='contactsPage'),
    path('desk/<str:pk>/', views.DeskView.as_view(), name='deskPage'),
    path('sofa/<str:pk>/', views.SofaView.as_view(), name='sofaPage'),
    path('wordrope/<str:pk>/', views.WordropeView.as_view(), name='wordropePage'),
    path('face_recognition/', views.face, name='face'),
    path('login/', views.login_view, name='login'),
    # path('logout', views.logout_view, name='logout'),
    path('classify/', views.find_user_view, name='classify'),

]


urlpatterns += staticfiles_urlpatterns()
urlpatterns = format_suffix_patterns(urlpatterns)

facialRecognitionSite/models.py
from django.db import models

# Create your models here.
class User(models.Model):
    id = models.AutoField(primary_key=True)
    username = models.CharField(max_length=255,blank=True,null=True)
    email = models.EmailField(blank=True, null=True)
    password = models.CharField(max_length=255, blank=True, null=True)
    image = models.ImageField(upload_to='photos',  blank=True, null=True)
    
    def __str__(self):
        return self.username

facialRecognitionSite/forms.py
from django import forms
from django.forms import ModelForm
from .models import *
from rest_framework import serializers


class UserForm(ModelForm):
    class Meta:
        model = User
        fields = "__all__"

facialRecognitionSite/views.py
from os import path
from urllib.request import urlopen
from django.shortcuts import render, redirect
from django.views.generic import TemplateView

from .models import *
from django.contrib.auth import logout
from django.contrib.auth.decorators import login_required
from django.http import JsonResponse
from django.core.files import File
from django.core.files.base import ContentFile
from django.core.files.temp import NamedTemporaryFile
from .forms import *
from django.contrib import messages
import face_recognition
import cv2
import numpy as np



def get_user(users):
    auth_user = []
    for user in users:
        # Load a sample picture and learn how to recognize it.
        try:
            sample_image = face_recognition.load_image_file(f".{user.image.url}")
            sample_face_encoding = face_recognition.face_encodings(sample_image)[0]
            auth_user.append(user)
        except:
            pass
    return auth_user

def face(request):
    video_capture = cv2.VideoCapture(0)
    if not video_capture.isOpened():
        raise IOError("Cannot open webcam")

    users = User.objects.all()
    known_face_encodings=[]
    known_face_names=[]
    sample_image_containers = []
    sample_face_encoding_containers = []
    context ={}
    pk=0
   
    for user in get_user(users):
    # Load a sample picture and learn how to recognize it.
        sample_image = face_recognition.load_image_file(f".{user.image.url}")
        sample_image_containers.append(sample_image)
        
        sample_face_encoding = face_recognition.face_encodings(sample_image)[0]
        
        sample_face_encoding_containers.append(sample_face_encoding)
        known_face_encodings.append(sample_face_encoding)
        known_face_names.append(str(user.id))
    face_locations = []
    face_encodings = []
    face_names = []
    process_this_frame = True

    while True:
        # Grab a single frame of video
        ret, frame = video_capture.read()

        # Only process every other frame of video to save time
        if process_this_frame:
           
            # Resize frame of video to 1/4 size for faster face recognition processing
            small_frame = cv2.resize(frame, (0, 0), fx=0.25, fy=0.25)

            # Convert the image from BGR color (which OpenCV uses) to RGB color (which face_recognition uses)
            # rgb_small_frame = small_frame[:, :, ::-1]
            rgb_small_frame = cv2.cvtColor(small_frame, cv2.COLOR_BGR2RGB)

            # Find all the faces and face encodings in the current frame of video
            face_locations = face_recognition.face_locations(rgb_small_frame)
            face_encodings = face_recognition.face_encodings(
                rgb_small_frame, face_locations)

            face_names = []
            for face_encoding in face_encodings:
                # See if the face is a match for the known face(s)
                matches = face_recognition.compare_faces(
                    known_face_encodings, face_encoding)
                name = "Unknown"

                # # If a match was found in known_face_encodings, just use the first one.
                # if True in matches:
                #     first_match_index = matches.index(True)
                #     name = known_face_names[first_match_index]

                # Or instead, use the known face with the smallest distance to the new face
                face_distances = face_recognition.face_distance(
                    known_face_encodings, face_encoding)
                best_match_index = np.argmin(face_distances)
                if matches[best_match_index]:
                    name = known_face_names[best_match_index]

                face_names.append(name)

        process_this_frame = not process_this_frame

        # Display the results
        for (top, right, bottom, left), name in zip(face_locations, face_names):
            # Scale back up face locations since the frame we detected in was scaled to 1/4 size
            top *= 4
            right *= 4
            bottom *= 4
            left *= 4

            # Draw a box around the face
            cv2.rectangle(frame, (left, top), (right, bottom), (0, 0, 255), 2)

            # Draw a label with a name below the face
            cv2.rectangle(frame, (left, bottom - 35),
                        (right, bottom), (0, 0, 255), cv2.FILLED)
            font = cv2.FONT_HERSHEY_DUPLEX
            cv2.putText(frame, name, (left + 6, bottom - 6),
                        font, 1.0, (255, 255, 255), 1)

        # Display the resulting image
        cv2.imshow('Video', frame)
        
        if face_names:
            if face_names[0] != 'Unknown':
                logged_user = User.objects.filter(id=face_names[0])
                pk = logged_user[0].id
                print(pk)
                break

        # Hit 'q' on the keyboard to quit!
        if cv2.waitKey(1) & 0xFF == ord('q'):    
            break
        
    # Release handle to the webcam
    video_capture.release()
    cv2.destroyAllWindows()
    
    if pk == 0:
        return render(request, 'login.html', {})
    else:
        return redirect('facialRocognitionUrls:indexPage',pk)



def login_view(request):
    return render(request, 'login.html', {})


def logout_view(request):
    logout(request)
    redirect('login')


def find_user_view(request):
    # if able to find user
    return JsonResponse({'sucsess': True})


# @login_required
def home_view(request,pk):
    logged = User.objects.get(id = pk) 
    return render(request, 'index.html', {'pk':pk,'logged':logged})


class AboutView(TemplateView):
    template_name = 'about.html'
    def get(self,request,pk):
        logged = User.objects.get(id = pk) 
        return render(request, 'about.html', {'pk':pk,'logged':logged})



class AccountView(TemplateView):
    template_name = 'account.html'

    def post(self, request, format=None):
        user = UserForm(request.POST, request.FILES)
        # messages.success(request, f"{request.POST},{request.FILES}")
        if user.is_valid():
            user.save()
            return render(request, 'login.html', {})
        else:
            return render(request, 'account.html', {})


class BedView(TemplateView):
    template_name = 'bed.html'

    def get(self, request, pk):
        logged = User.objects.get(id=pk)
        return render(request, 'bed.html', {'pk': pk, 'logged': logged})



class ChairView(TemplateView):
    template_name = 'chair.html'

    def get(self, request, pk):
        logged = User.objects.get(id=pk)
        return render(request, 'chair.html', {'pk': pk, 'logged': logged})



class ContactsView(TemplateView):
    template_name = 'contacts.html'

    def get(self, request, pk):
        logged = User.objects.get(id=pk)
        return render(request, 'contacts.html', {'pk': pk, 'logged': logged})




class DeskView(TemplateView):
    template_name = 'desk.html'

    def get(self, request, pk):
        logged = User.objects.get(id=pk)
        return render(request, 'desk.html', {'pk': pk, 'logged': logged})



class SofaView(TemplateView):
    template_name = 'sofa.html'

    def get(self, request, pk):
        logged = User.objects.get(id=pk)
        return render(request, 'sofa.html', {'pk': pk, 'logged': logged})



class WordropeView(TemplateView):
    template_name = 'wordrope.html'

    def get(self, request, pk):
        logged = User.objects.get(id=pk)
        return render(request, 'wordrope.html', {'pk': pk, 'logged': logged})

facialRecognitionSite/templates/about.html
{% extends 'base.html' %}
{% load static %}
{% block style%}
{% static 'css/style.css' %}
{% endblock %}
{% block content %} 
    <!-- landing page -->
    <div class="container">
            {% include 'nav.html' %}

    </div>

    <div class="container2">
        <div class="model">
        <h1>cart</h1>
        <br />

        <div class="cart">
            <header>
                <div>PRODUCT</div>
                <div>PRICE</div>
                <div>QUANTITY</div>
            </header>
            <br>
            <div class="cart-items">

                <!-- <div class="hori-1">
                    <div class="items">
                        <img src="../IMAGES/w1.jpg" alt="">
                        <p>product name</p>
                    </div>

                    <div class="price">
                        <p>GH₵<span class="cart-price">450</span></p>
                    </div>

                    <div class="quantity">
                        <input type="number" class="cart-quantity-input" name="" id="numb" value="1">
                        <button class="rm" id="remove">Remove</button>
                    </div>
                </div>  --> 
            </div>
            <br>
            <div class="total">
                <p>total: GH₵<span class="sum">00.00</span></p>
            </div>

            <br>
            <div class="purchase">
                <button class="purchase">check out</button>
            </div>
        </div>
        
        <br />
        <button id="close">close</button>
        </div>
    </div>
    </div>


    <div class="cont">
        <h1>About Us</h1>
        <br>
        <p>DreamWoodz is a platform for furniture manufacturers 
             who would like to advertise <br> furniture products as well as 
             customers who seek quality and affordable furniture <br> for upmost comfort. 
             The app is a web app geared towards the provision of furnished <br>furniture ware 
             such as office chairs and tables, dining tables and chairs, <br>
              beds, and the like to customers. The web app allows customers to purchase goods <br>
              from the comfort of their homes. </p>

        
    </div>



    <footer>
        <p>&copy 2021 DreamWoodz</p> 
    </footer>
    
{% endblock %}
    

facialRecognitionSite/templates/account.html
{% extends 'base.html' %}
{% load static %}

{% block style %}
{% static 'css/style.css' %}
{% endblock %}

{% block content %} 
<!-- landing page -->
<div class="container">
     

</div>
<main>

    <div class="container-f">
        <div class="header">
            <h2>Create Account</h2>
        </div>
        <form action="{% url 'facialRocognitionUrls:accountPage' %}" method="post" id="form" class="form" enctype="multipart/form-data">
            {% csrf_token %} 
            <div class="form-control">
                <label for="username">Username</label>
                <input type="text" placeholder="Username" id="username" name="username" />
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            <div class="form-control">
                <label for="email">Email</label>
                <input type="email" placeholder="example@gmail.com" id="email" name="email"/>
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            <div class="form-control">
                <label for="password">Password</label>
                <input type="password" placeholder="Password" id="password" />
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            <div class="form-control">
                <label for="password">Confirm Password</label>
                <input type="password" placeholder="Password" id="password2" name="password"/>
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                <small>Error message</small>
            </div>
            <div class="form-control">
                <label for="picture">Upload Picture</label>
                <input type="file"  accept = "image/*"  name="image" required/>
                <i class="fas fa-check-circle"></i>
                <i class="fas fa-exclamation-circle"></i>
                
            </div>
            <button class="ac-submit" type="submit">Submit</button>
            
            
        </form>

    </div>
    
</main>
{% endblock %}

facialRecognitionSite/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/@fortawesome/fontawesome-free@5.15.3/css/fontawesome.min.css" integrity="undefined" crossorigin="anonymous">
<link rel="stylesheet" href="{% block style %}{% endblock %}">
<link rel="stylesheet" href="{% block account %}{% endblock %}">
<link rel="stylesheet" href="{% block facial %}{% endblock %}">

<title>DreamWoodz</title>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</head>
<body>
{% block content %}
{% endblock %}
</body>
<script src="{% static 'js/main.js' %}" async></script>
<script src="{% static 'js/contact.js' %}"></script>
</html>

facialRecognitionSite/templates/contacts.html
{% extends 'base.html' %}
{% load static %}
{% block style%}
{% static 'css/style.css' %}
{% endblock %}
{% block content %} 
<!-- landing page -->
<div class="container">
        {% include 'nav.html' %}

</div>
<main>

    <div class="container-m">
        <div class="header">
            <h2>Contact Us</h2>
        </div>
        <form id="form" class="form">
            <div class="form-control">
                <label for="username">Username</label>
                <input type="text" placeholder="Username" id="username" />
                
            </div>
            <div class="form-control">
                <label for="username">Email</label>
                <input type="email" placeholder="example@gmail.com" id="email" />
                
            </div>
            
            <div class="form-control">
                <label for="message">Message</label>
                <br>
                <textarea name="message" id="" cols="108" rows="10"></textarea>
            </div>
            
            <button class="ac-submit">Send</button>
        </form>
    </div>
    
</main>
{% endblock %}

facialRecognitionSite/templates/login.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
<meta charset="UTF-8">
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta http-equiv="X-UA-Compatible" content="ie=edge">
<meta name="Description" content="Enter your description here"/>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/css/bootstrap.min.css">
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.4/css/all.min.css">
<link rel="stylesheet" href="{% static 'css/login.css' %}">

<title>Login</title>
</head>
<body>
{% comment %} 
<div class="text-center">

<video autoplay = "true" id="vidoe-element"></video>
</div>


<div id="img-element"></div>

<canvas id="canvas" width="320" height="240"></canvas>
<div class = "text-center mt-3">
   
    <button class="btn btn-primary" id="capture-btn">
        take photo
    
    </button>
    
    <button class="btn btn-info" id="reload-btn">
       reload
    
    </button>


</div> {% endcomment %}


<div class="text-center login" >
<h1>Login</h1>
<h4>Welcome to DreamWoodz click the login button below to log into your account using facial recognition
</h4>

<h5>NB:Please note that the facial recognition feature
    may take sometime to load depending on the 
    hardware requirements of your machine
</h5>
<a class="btn btn-primary" id="start-camera" href="{% url 'facialRocognitionUrls:face' %}">login</a>
<h5>If you don't have an account yet you can press the
    letter "q" on your keyboard to close the facial recognition
feature and create an <a href="{% url 'facialRocognitionUrls:accountPage' %}">account</a>  first.
</h5>
</h5>
</div> 

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/twitter-bootstrap/3.3.7/js/bootstrap.min.js"></script>
</body>
</html>

facialRecognitionSite/templates/nav.html
<div class="navbar">
        <div class="logo">
            <p><a href="{% url 'facialRocognitionUrls:indexPage' pk %}">DreamWoodz,{{logged.username}}</a> </p>
            

        </div>
        <nav>
            <ul>
                <li><a href="{% url 'facialRocognitionUrls:indexPage' pk %}">home</a></li>
                <li><a href="{% url 'facialRocognitionUrls:aboutPage' pk %}">about</a></li>
                <li><a href="{% url 'facialRocognitionUrls:accountPage' %}">account</a></li>
                <li><a href="{% url 'facialRocognitionUrls:contactsPage' pk %}">contact</a></li>
                <li><a href="{% url 'facialRocognitionUrls:login'%}">logout</a></li>

            </ul>
        </nav>
        
       <img id="cart" class="cart-img" src="https://img.icons8.com/android/24/4a90e2/shopping-cart.png" alt="cart"/>
    </div>